---

- name: Generate temporary SSH keys
  command: "ssh-keygen -t rsa -b 2048 -N '' -f {{ ansible_user_dir }}/id_rsa"

- name: Store public key variable
  command: "cat {{ ansible_user_dir }}/id_rsa.pub"
  register: generate_ssh_keys_pubkey
