---

- name: Generate temporary SSH keys in /tmp
  command: "ssh-keygen -t rsa -b 2048 -N '' -f {{ ansible_user_dir }}/id_rsa"

- name: Store generate-ssh-keys_privkey variable
  command: "cat {{ ansible_user_dir }}/id_rsa"
  register: generate_ssh_keys_privkey

- name: Store generate-ssh-keys_pubkey variable
  command: "cat {{ ansible_user_dir }}/id_rsa.pub"
  register: generate_ssh_keys_pubkey
