---

- name: Generate temporary SSH keys
  command: "ssh-keygen -t rsa -b 2048 -N ''"

- name: Store public key variable
  command: "cat {{ ansible_user_dir }}/.ssh/id_rsa.pub"
  register: generate_ssh_keys_pubkey
