---

- name: Uninstall system wide Ansible just in case
  package:
    name: ansible
    state: absent
  become: yes

- name: Install the required version of Ansible
  pip:
    name: "{{ ansible_pip_package }}"
    extra_args: --user
    state: forcereinstall
    executable: "{{ pip }}"
