---

- name: Generate push config playbook
  template:
    src: "{{ network_os }}/push_config.j2"
    dest: "{{ ansible_user_dir }}/push_config.yaml"

- command: "cat {{ ansible_user_dir }}/push_config.yaml"

- name: Run push config playbook to inject new key
  command: "{{ ansible_user_dir }}/.local/bin/ansible-playbook --private-key=ansible-images -i inventory push_config.yaml -vvvv"
  args:
    chdir: "{{ ansible_user_dir }}"
