---

- name: Install required Ansible Network libs
  pip:
    name: "{{ item }}"
    extra_args: --user
    state: forcereinstall
    executable: "{{ pip }}"
  with_items:
    - jxmlease
    - ncclient
