- hosts: controller

  tasks:
    - include_role:
        role: dump-ansible-images-keys
    - include_role:
        role: generate-ssh-keys
    - debug: var=hostvars['controller']['ansible_user_dir']
    - debug: var="{{ lookup('pipe', 'cat ' + hostvars['controller']['ansible_user_dir']) }}"
    - debug: var="{{ lookup('file', ansible_user_dir + '/id_rsa.pub') }}"

- hosts: appliance
  gather_facts: no

  tasks:
    - include_role:
        role: inject-pubkey-on-appliance
      vars:
        pubkey: "{{ lookup('file', ansible_user_dir + '/id_rsa.pub') }}"

- hosts: controller

  tasks:
    - include_role:
        role: remove-ansible-images-keys
