- hosts: controller

  tasks:
    - include_role:
        role: dump-ansible-images-keys
    - include_role:
        role: generate-ssh-keys

- hosts: appliance
  gather_facts: no

  tasks:
    - include_role:
        role: inject-pubkey-on-appliance
      vars:
        pubkey: "{{ generate_ssh_keys_pubkey }}"

- hosts: controller

  tasks:
    - include_role:
        role: remove-ansible-images-keys
