- hosts: controller

  tasks:
    - include_role:
        role: dump-ansible-images-keys
    - include_role:
        role: generate-ssh-keys
    - include_role:
        role: generate-appliance-inventory
    - command: "cat {{ ansible_user_dir }}/inventory"
    - include_role:
        role: inject-pubkey-on-appliance
      vars:
        pubkey: generate_ssh_keys_pubkey
    - include_role:
        role: remove-ansible-images-keys
