- hosts: controller

  tasks:
    - include_role:
        role: dump-ansible-images-keys
    - include_role:
        role: generate-ssh-keys

- hosts: appliance
  gather_facts: no

  tasks:
    - name: Store generate-ssh-keys_pubkey variable
        command: cat /tmp/id_rsa.pub
      register: generate_ssh_keys_pubkey
    - include_role:
        role: inject-pubkey-on-appliance

- hosts: controller

  tasks:
    - include_role:
        role: remove-ansible-images-keys
